apiVersion: apps/v1
kind: Deployment
metadata:
  name: cosmosdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cosmosdb
  template:
    metadata:
      labels:
        app: cosmosdb
    spec:
      containers:
      - name: cosmosdb
        image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
        ports:
        - containerPort: 8081
        env:
        - name: AZURE_COSMOS_EMULATOR_PARTITION_COUNT
          value: "1"
        - name: AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE
          value: "true"
        - name: AZURE_COSMOS_EMULATOR_NO_SSL
          value: "true"
        volumeMounts:
        - name: cosmosdb-data
          mountPath: /data
      volumes:
      - name: cosmosdb-data
        persistentVolumeClaim:
          claimName: cosmosdb-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cosmosdb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: cosmosdb
spec:
  selector:
    app: cosmosdb
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
