apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-gateway-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-gateway-api
  template:
    metadata:
      labels:
        app: payment-gateway-api
    spec:
      containers:
      - name: payment-gateway-api
        image: paymentgateway/api:latest
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: payment-gateway-api
spec:
  selector:
    app: payment-gateway-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
